# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_site.Project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_site.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='phone',
            field=models.CharField(default='phone', max_length=10),
        ),
        migrations.AddField(
            model_name='developer',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 9, 13)),
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_site.Developer'),
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_site.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_site.Developer'),
        ),
    ]
