# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills_site', '0002_auto_20160913_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
    ]
